name: LastMinute
description: LastMinute Application.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    intl:
    flutter_colorpicker: ^0.6.0
    calendar_view: any
    firebase_core: ^2.4.1
    flutterfly: ^0.2.0+10
    flutter_firebase_chat_core: ^1.6.4
    firebase_auth: ^4.1.0
    google_sign_in: ^5.4.3
    provider: ^6.0.1
    font_awesome_flutter: ^9.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: ^2.0.6
    build_web_compilers: ^3.0.0

flutter:
    uses-material-design: true
