// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU5Wj4TmuwtVlO4Egs5siQWIVF1M8wQtQ',
    appId: '1:676919463381:web:994b37cc42bdbcbf26815c',
    messagingSenderId: '676919463381',
    projectId: 'last-minute-5909a',
    authDomain: 'last-minute-5909a.firebaseapp.com',
    storageBucket: 'last-minute-5909a.appspot.com',
    measurementId: 'G-1BL0V0YGVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjGV2TpAN3n45SWH0fs_w3XCvK3LyfqCA',
    appId: '1:676919463381:android:8a25ab531014ffc426815c',
    messagingSenderId: '676919463381',
    projectId: 'last-minute-5909a',
    storageBucket: 'last-minute-5909a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrQf-vTHCYOF4vZ57peaLen592jsbrV1U',
    appId: '1:676919463381:ios:8e044c5fa010be3e26815c',
    messagingSenderId: '676919463381',
    projectId: 'last-minute-5909a',
    storageBucket: 'last-minute-5909a.appspot.com',
    iosClientId: '676919463381-488nti58vp9ua6jvefbq2eih8tctc4tt.apps.googleusercontent.com',
    iosBundleId: 'com.calendar.page.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrQf-vTHCYOF4vZ57peaLen592jsbrV1U',
    appId: '1:676919463381:ios:8e044c5fa010be3e26815c',
    messagingSenderId: '676919463381',
    projectId: 'last-minute-5909a',
    storageBucket: 'last-minute-5909a.appspot.com',
    iosClientId: '676919463381-488nti58vp9ua6jvefbq2eih8tctc4tt.apps.googleusercontent.com',
    iosBundleId: 'com.calendar.page.example.example',
  );
}
